### ISSUE TITLE
pdfjs Print-Logo Zoom- und Suchfunktionalität

### ISSUE THREAD

**Issue by bierik** [4teamwork/ftw.showroom#15]
Mit @jone Besprechen welche Funktionlität wir für GEVER oder Teamraum im pdfjs aktivieren wollen.

Dazu gehören:
- Print logo
- Zoom
- Suche

**Comment by jone** [comment]
@bierik siehe dazu: https://basecamp.com/2768704/projects/7760630/messages/57215204

**Comment by bierik** [comment]
The style in bumblebee can now be changed since https://github.com/senny/pdfjs_viewer-rails/pull/17
